export const NOTES_FETCH_SUCCESS = 'NOTES_FETCH_SUCCESS';

export const NOTE_HISTORY_FETCH_SUCCESS = 'NOTE_HISTORY_FETCH_SUCCESS';

export const NOTE_FETCH_SUCCESS = 'NOTE_FETCH_SUCCESS';

export const NOTE_SELECTED = 'NOTE_SELECTED';
